<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="11" passed="0" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-15T21:16:48Z" name="Sanity Suite to run single test cases with test name in method" finished-at="2021-10-15T21:17:05Z" duration-ms="17468">
    <groups>
    </groups>
    <test started-at="2021-10-15T21:16:48Z" name="Verify that user is able to remove products from Cart" finished-at="2021-10-15T21:17:05Z" duration-ms="17468">
      <class name="com.ziegertEverEstate.qa.tests.ProductPageTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:48Z" name="setup" finished-at="2021-10-16T02:46:51Z" duration-ms="2550" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_user_is_able_to_remove_product_from_cart(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:51Z" name="verify_user_is_able_to_remove_product_from_cart" description="Verify that user is able to remove products from Cart" data-provider="getproductsAndQuantityData" finished-at="2021-10-16T02:46:51Z" duration-ms="875" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Wine Skul T-Shirt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[$ 13.25]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$ 0.01] but found [$ 0.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$ 0.01] but found [$ 0.00]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.ziegertEverEstate.qa.tests.ProductPageTests.verify_user_is_able_to_remove_product_from_cart(ProductPageTests.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_user_is_able_to_remove_product_from_cart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:51Z" name="tearDown" finished-at="2021-10-16T02:46:52Z" duration-ms="610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:52Z" name="setup" finished-at="2021-10-16T02:46:54Z" duration-ms="1924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_user_is_able_to_remove_product_from_cart(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:54Z" name="verify_user_is_able_to_remove_product_from_cart" description="Verify that user is able to remove products from Cart" data-provider="getproductsAndQuantityData" finished-at="2021-10-16T02:46:55Z" duration-ms="879" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Wine Skul T-Shirt]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[$ 13.25]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$ 0.01] but found [$ 0.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$ 0.01] but found [$ 0.00]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.ziegertEverEstate.qa.tests.ProductPageTests.verify_user_is_able_to_remove_product_from_cart(ProductPageTests.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_user_is_able_to_remove_product_from_cart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:55Z" name="tearDown" finished-at="2021-10-16T02:46:56Z" duration-ms="601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:56Z" name="setup" finished-at="2021-10-16T02:46:58Z" duration-ms="1955" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_user_is_able_to_remove_product_from_cart(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:58Z" name="verify_user_is_able_to_remove_product_from_cart" description="Verify that user is able to remove products from Cart" data-provider="getproductsAndQuantityData" finished-at="2021-10-16T02:46:59Z" duration-ms="866" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[White DGK Script Tee]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[$ 29.80]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$ 0.01] but found [$ 0.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$ 0.01] but found [$ 0.00]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.ziegertEverEstate.qa.tests.ProductPageTests.verify_user_is_able_to_remove_product_from_cart(ProductPageTests.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_user_is_able_to_remove_product_from_cart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:59Z" name="tearDown" finished-at="2021-10-16T02:46:59Z" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:46:59Z" name="setup" finished-at="2021-10-16T02:47:03Z" duration-ms="3754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_user_is_able_to_remove_product_from_cart(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:47:03Z" name="verify_user_is_able_to_remove_product_from_cart" description="Verify that user is able to remove products from Cart" data-provider="getproductsAndQuantityData" finished-at="2021-10-16T02:47:04Z" duration-ms="928" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[White DGK Script Tee]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[$ 29.80]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [$ 0.01] but found [$ 0.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [$ 0.01] but found [$ 0.00]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.ziegertEverEstate.qa.tests.ProductPageTests.verify_user_is_able_to_remove_product_from_cart(ProductPageTests.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_user_is_able_to_remove_product_from_cart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ziegertEverEstate.qa.tests.ProductPageTests@18d87d80]" started-at="2021-10-16T02:47:04Z" name="tearDown" finished-at="2021-10-16T02:47:05Z" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ziegertEverEstate.qa.tests.ProductPageTests -->
    </test> <!-- Verify that user is able to remove products from Cart -->
  </suite> <!-- Sanity Suite to run single test cases with test name in method -->
</testng-results>
